import Head from "next/head";
export default function Wanderlust() {
  return (
    <>
      <Head>
        <title>🏖️ Wanderlust</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-full h-[100vh] m-auto">
        <div className="content flex flex-row max-h-[92vh]  h-[calc(100vh_-_5rem)]">
          <div className="map-wrapper w-full">Wanderlust map</div>
        </div>
      </main>
    </>
  );
}
