import { Metadata } from "next";

export const metadata: Metadata = {
  title: "My Page Title",
};

import Head from "next/head";
import { Button, Drawer } from "antd";
import dynamic from "next/dynamic";
import SearchBar from "../../components/SearchBar";
import { useState } from "react";
import { useRecoilState } from "recoil";
import { placeState } from "../../atoms/atom";
import useFetchPlaces from "hooks/useFetchPlaces";
import RestaurantList from "components/RestaurantList";
import PageFooter from "components/PageFooter";

const AMapComponent = dynamic(() => import("../../components/AMap"), {
  ssr: false,
});
const InfoPanel = dynamic(() => import("../../components/InfoPanel"), {
  ssr: false,
});

export default function Page() {
  const [currentPoi, setCurrentPoi] = useState({});
  const clickPoiMaker = (poi: any) => setCurrentPoi(poi);
  const [place] = useRecoilState(placeState);

  const { data } = useFetchPlaces(place, false);

  console.log({ data });
  const { pois = [] } = data;

  const [open, setOpen] = useState(false);

  const showDrawer = () => {
    setOpen(true);
  };

  const onClose = () => {
    setOpen(false);
  };

  return (
    <>
      <Head>
        <title>🥘 What to eat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-full h-[100vh] m-auto">
        <div className="content flex flex-row max-h-[92vh]  h-[calc(100vh_-_5rem)]">
          <div className="banner mx-4 flex flex-col text-xl">
            <SearchBar />
            <RestaurantList pois={pois} poiClick={clickPoiMaker} />
            <InfoPanel restaurantInfo={currentPoi} addressArr={[]} />
          </div>
          <div className="map-wrapper w-full">
            <AMapComponent poiClick={clickPoiMaker} pois={pois} />
          </div>

          <Button
            type="primary"
            onClick={showDrawer}
            className="absolute right-4 top-4"
          >
            Add addresses
          </Button>
          <Drawer
            title="Basic Drawer"
            placement="right"
            onClose={onClose}
            open={open}
          >
            <p>Some contents...</p>
            <p>Some contents...</p>
            <p>Some contents...</p>
          </Drawer>
        </div>
        <div className="">
          <PageFooter />
        </div>
      </main>
    </>
  );
}
