import Head from "next/head";
import { Button, Drawer } from "antd";
import dynamic from "next/dynamic";
import SearchBar from "../components/SearchBar";
import { FC, useEffect, useState } from "react";
import { useRecoilState } from "recoil";
import { placeState } from "../atoms/atom";
import useFetchPlaces from "hooks/useFetchPlaces";
import RestaurantList from "components/RestaurantList";

const AMapComponent = dynamic(() => import("../components/AMap"), {
  ssr: false,
});
const InfoPanel = dynamic(() => import("../components/InfoPanel"), {
  ssr: false,
});

export default function Home() {
  const [currentPoi, setCurrentPoi] = useState({});
  const clickPoiMaker = (poi: any) => setCurrentPoi(poi);
  const [place] = useRecoilState(placeState);

  const { data } = useFetchPlaces(place);

  console.log({ data });
  const { pois = [] } = data;

  const [open, setOpen] = useState(false);

  const showDrawer = () => {
    setOpen(true);
  };

  const onClose = () => {
    setOpen(false);
  };

  return (
    <>
      <Head>
        <title>Have a good dinner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main  flex flex-row w-full h-[100vh] m-auto">
        <div className="banner mx-4 flex flex-col text-xl">
          <div className="mx-2 my-4">What to eat?</div>
          <SearchBar />
          <RestaurantList pois={pois} />
          <InfoPanel restaurantInfo={currentPoi} addressArr={[]} />
        </div>
        <div className="map-wrapper w-full h-full">
          <AMapComponent poiClick={clickPoiMaker} pois={pois} />
        </div>
        <div>
          <Button type="primary" onClick={showDrawer}>
            Open
          </Button>
          <Drawer
            title="Basic Drawer"
            placement="right"
            onClose={onClose}
            open={open}
          >
            <p>Some contents...</p>
            <p>Some contents...</p>
            <p>Some contents...</p>
          </Drawer>
        </div>
      </main>
    </>
  );
}
